#!/usr/bin/env sh

# global settings
yabai -m config debug_output on

# mouse settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follow_mouse           off 

# tiling settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   06

